try {
    throw new Error("Throw an exception Masud"); 
 }
 catch (e) {
    console.log(e); 
 }